sudo: required 
language: generic
services: 
        - docker 

before_install: 
        - docker build -t p20min/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true p20min/docker-react npm run test

deploy: 
        provider: elasticbeanstalk
        region: "eu-central-1"
        app: "docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-eu-central-1-496870371832"
        bucket_path: "docker-react"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key: $AWS_SECRET_KEY
